---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "Tracy d'Arbeloff"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Department of Psychology and Neuroscience \n Duke University \n Durham, NC 27708, USA"
    email         : "Tracy.Darbeloff@Duke.edu"
  - name          : "Katie Freedy"
    affiliation   : "1"
  - name          : "Annchen Knodt"
    affiliation   : "1"
  - name          : "Spenser R. Radtke"
    affiliation   : "1"
  - name          : "Bartholomew D. Brigidi"
    affiliation   : "1"
  - name          : "Ahmad Hariri"
    affiliation   : "1"
    
affiliation:
  - id            : "1"
    institution   : "Laboratory of NeuroGenetics, Department of Psychology and Neuroscience, Duke University, Durham, NC 27708, USA"


author_note: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Enter abstract here. Each new line herein must be indented, like this line.
  
keywords          : "keywords"
wordcount         : "X"


figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
mask              : no

class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
source("PAPER_Mediation.R")
```

# Methods

## Participants
Data were available from 544 undergraduate students (337 women, age range = 18-22 years old, mean age = 19.64) who had participated in the Duke Neurogenetics Study (DNS) between September 30th, 2014 and November 21st, 2016 and had completed specific self-report questionnaires at two different time points. 
In accordance with the Duke University Medical Center Institutional Review Board guidelines, all participants provided informed, written consent. To be eligable for participation in the DNS, participants were required to be free of the following conditions: 1) medical diagnoses of cancer, stroke, head injury with loss of consciousness, untreated migraine headaches, diabetes requiring insulin treatment, chronic kidney or liver disease; 2) use of psychotropic, glucocorticoid, or hypolipidemic medication; and 3) conditions affecting cerebreal blood flow and metabolism (e.g., hypertension).

## Self-Report Questionnaires
The Mood and Anxiety Questionnaire (MASQ) Short Form is a 62-item self-report questionnaire used to assess current anxious and depressive symptoms over the past week. Symptoms of depression and anxiety are scored along four subscales: two General Distress factors (22 items, 11 assessing symptoms relative to depression and 12 assessing symptoms relative to anxiety), an Anxious Arousal factor (17 items), which is specific to anxious symptoms, and an Anhedonic Depression factor (22 items) specific to depression. (REF?)  A total MASQ score is generated by summing all items across the 4 subscales.  Items are rated on a 5-point scale ranging from 1 (not at all) to 5 (extremely).  To comply with IRB protocol, one item on the Anhedonic Depression subscale relating to suicidality was removed.

The Emotion Regulation Questionnaire (ERQ) is a 10-item self-report questionnaire used to measure individual differences in two divergent emotion regulation strategies: Cognitive Reappraisal (6 items) and Expressive Suppression (4 items). (REF?)  Items are rated on a 7-point scale from 1 (strongly disagree) to 7 (strongly agree).

The Interpersonal Support Evaluation List (ISEL) is a 12-item self-report questionnaire used to measure an individual's perception of social support.(REF?) Items are rated on a 4 point scale ranging from 0 (Definitely False) to 3 (Definitely True). 

## Data analysis
Multiple Linear regression was performed using the programming language R(v.3.4.4) to test whether relationships existed between ERQ Suppression and Reappraisal, MASQ (current(T1) and future(T2)), and ISEL. Age, Sex, and Diagnoses were included as additional covariates to control for any potential confounds within the model. All variable distributions were checked for normality and z-scored to standardize betas.

# Results

## Behavioral Measures
Means and standard deviations for relevant variables are as follows: MASQ total score timepoint 1 (T1)(`r descMASQT1$mean`± `r descMASQT1$sd`, range = 147); MASQ total score timepoint 2 (T2)(`r descMASQT2$mean` ± `r descMASQT2$sd`, range = 179); ERQ Reappraisal (`r descERQr$mean` ± `r descERQr$sd`, range = 5.5); ERQ Suppression (`r descERQs$mean` ± `r descERQs$sd`, range = 6); ISEL (`r descISEL$mean` ± `r descISEL$sd`, range = 31). MASQ (T1) significantly predicted MASQ (T2) ($\beta$ = `r betas_MASQ$estimate[2]`, *p* < 0.001), and explained 28% of the variance ($R^2$(539) = `r func_MASQ$adj.r.squared`, *p*< 0.001).
There were no significant sex differences for MASQ(T1) or MASQ(T2). However, Average ERQ Reappraisal subscale scores for men (M = 5.06, SD = 1.02) and women (M = 5.30, SD = 0.85) significantly differed (*t*(379.57) = 2.71, *p* = 0.004). Average ERQ Suppression subscale scores also differed (*t*(459.8)= -4.40, *p* < 0.001), with women (M = 3.61, SD = 1.24) scoring significantly lower than men (M = 4.07, SD = 1.16). There were significant sex differences between men and women in the ISEL scale (*t*(399.28)= 3.8151, *p* < 0.001), with women (M = 28.80, SD = 5.44) scoring significantly higher than men (M = 26.83, SD = 6.08).

## Indirect Effects Model
Use of Reappraisal did not significantly predict future MASQ (T2) ($\beta$ = `r Betas_erqR$estimate[2]`, `r ERQrMASQ_pval`) when accounting for current symptoms ($\Delta R^2$ < 0.001, F(538) = 0.01, *p* = 0.91). However, ERQ reappraisal scores did significantly predict ISEL scores ($\beta$ = `r betasA$estimate[2]`, *p* < 0.001), accounting for around 10% of the variance ($R^2$(538) = `r FuncA$adj.r.squared`, *p*< 0.001). To complete the path, ISEL significantly predicted future MASQ (T2) ($\beta$ = `r betasB$estimate[2]`, *p* < 0.001) when controlling for current symptoms ($\Delta R^2$ .

Use of Suppression also did not significantly predict future MASQ (T2) ($\beta$ = `r betas_erqS$estimate[2]`, `r ERQsMASQ_pval`) when accounting for current symptoms ($\Delta R^2$ = .04, F(538) = 30.55, *p* < 0.001). Again, however, ERQ suppression scores did significantly predict ISEL scores ($\beta$ = `r betasA_sup$estimate[2]`, *p* < 0.001), explaining around 20% of the variance ($R^2$(538) = `r funcA_sup$adj.r.squared`, *p*< 0.001). ISEL, in turn, significantly predicted future depression, as stated above.

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
